name: Generate Snake Game

# Controls when the workflow will run
on:
  # Schedules the workflow to run every 5 minutes (minimum supported by GitHub Actions)
  schedule:
    - cron: "*/5 * * * *"
  # Triggers the workflow on push or pull request events but only for the "widgets" branch
  push:
    branches: [ "widgets-snake" ]
  pull_request:
    branches: [ "widgets-snake" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # Uses the Platane/snk action to generate the snake game
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit and push generated files to the dedicated branch `widgets-snake`
      - name: Commit and push generated files to widgets-snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Update snake game [skip ci]'
          add: 'dist/**'
          branch: 'widgets-snake'
          token: ${{ secrets.GITHUB_TOKEN }}
